CREATE TABLE CATEGORY_MASTER(
	CATEGORY_ID VARCHAR(6) PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL
);

INSERT INTO CATEGORY_MASTER VALUES('CAT001','Refrigerator'),('CAT002','Washing Machine'),('CAT003','Air Conditioners'),('CAT004','Digital Cameras'),('CAT005','Television');
