CREATE TABLE SCHEME_MASTER (
	SCHEME_ID VARCHAR(6) PRIMARY KEY,
    DESCRIPTION VARCHAR(25)
);

INSERT INTO SCHEME_MASTER VALUES('SCH001','Buy One Take One Free'),('SCH002','50% Discount'),('SCH003','20% Discount'),('SCH004','One Bowl Free'),('SCH005','Two Glasses Free');